-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categoria
(
    id_categoria serial NOT NULL,
    nombre character varying(80) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT categoria_pkey PRIMARY KEY (id_categoria),
    CONSTRAINT categoria_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.cotizacion
(
    id_cotizacion serial NOT NULL,
    id_cliente integer NOT NULL,
    id_servicio integer NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL DEFAULT now(),
    estado character varying(15) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDIENTE'::character varying,
    subtotal numeric(12, 2) DEFAULT 0,
    descuento numeric(12, 2) DEFAULT 0,
    total numeric(12, 2) DEFAULT 0,
    CONSTRAINT cotizacion_pkey PRIMARY KEY (id_cotizacion)
);

CREATE TABLE IF NOT EXISTS public.cotizacion_detalle
(
    id_detalle serial NOT NULL,
    id_cotizacion integer NOT NULL,
    id_producto integer NOT NULL,
    descripcion character varying(200) COLLATE pg_catalog."default",
    cantidad numeric(12, 3) NOT NULL,
    precio_unit numeric(12, 2) NOT NULL,
    descuento numeric(12, 2) DEFAULT 0,
    subtotal numeric(12, 2) NOT NULL,
    CONSTRAINT cotizacion_detalle_pkey PRIMARY KEY (id_detalle)
);

CREATE TABLE IF NOT EXISTS public.cuota
(
    id_cuota serial NOT NULL,
    id_plan integer NOT NULL,
    numero_cuota integer NOT NULL,
    fecha_vencimiento date NOT NULL,
    monto numeric(12, 2) NOT NULL,
    estado character varying(15) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDIENTE'::character varying,
    fecha_pago date,
    observacion character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT cuota_pkey PRIMARY KEY (id_cuota)
);

CREATE TABLE IF NOT EXISTS public.cuota_pago
(
    id_cuota integer NOT NULL,
    id_recibo integer NOT NULL,
    monto_pagado numeric(12, 2) NOT NULL,
    CONSTRAINT cuota_pago_pkey PRIMARY KEY (id_cuota, id_recibo)
);

CREATE TABLE IF NOT EXISTS public.orden_trabajo_tecnico
(
    id_orden integer NOT NULL,
    id_tecnico integer NOT NULL,
    rol_en_orden character varying(50) COLLATE pg_catalog."default",
    horas_estimadas numeric(6, 2),
    CONSTRAINT orden_trabajo_tecnico_pkey PRIMARY KEY (id_orden, id_tecnico)
);

CREATE TABLE IF NOT EXISTS public.ordentrabajo
(
    id_orden serial NOT NULL,
    id_cotizacion integer NOT NULL,
    descripcion character varying(300) COLLATE pg_catalog."default",
    fecha_programada date,
    fecha_inicio timestamp without time zone,
    fecha_fin timestamp without time zone,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PROGRAMADA'::character varying,
    CONSTRAINT ordentrabajo_pkey PRIMARY KEY (id_orden)
);

CREATE TABLE IF NOT EXISTS public.plan_pago
(
    id_plan serial NOT NULL,
    id_venta integer NOT NULL,
    tipo_pago character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'CUOTAS'::character varying,
    cantidad_cuotas integer DEFAULT 1,
    monto_total numeric(12, 2) NOT NULL,
    monto_adelanto numeric(12, 2) DEFAULT 0,
    fecha_inicio date NOT NULL DEFAULT CURRENT_DATE,
    observacion character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT plan_pago_pkey PRIMARY KEY (id_plan)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    id_producto serial NOT NULL,
    nombre character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(300) COLLATE pg_catalog."default",
    precio_unit numeric(12, 2) NOT NULL,
    estado character varying(15) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVO'::character varying,
    id_categoria integer,
    stock integer DEFAULT 0,
    CONSTRAINT producto_pkey PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.recibo
(
    id_recibo serial NOT NULL,
    id_venta integer NOT NULL,
    fecha timestamp without time zone NOT NULL DEFAULT now(),
    total numeric(12, 2) NOT NULL,
    observacion character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT recibo_pkey PRIMARY KEY (id_recibo)
);

CREATE TABLE IF NOT EXISTS public.recibo_detalle_pago
(
    id_detalle serial NOT NULL,
    id_recibo integer NOT NULL,
    metodo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    monto numeric(12, 2) NOT NULL,
    referencia character varying(80) COLLATE pg_catalog."default",
    CONSTRAINT recibo_detalle_pago_pkey PRIMARY KEY (id_detalle)
);

CREATE TABLE IF NOT EXISTS public.rol
(
    id_rol serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT rol_pkey PRIMARY KEY (id_rol),
    CONSTRAINT rol_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.servicio
(
    id_servicio serial NOT NULL,
    nombre character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(300) COLLATE pg_catalog."default",
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    subtipo character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT servicio_pkey PRIMARY KEY (id_servicio)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    payload text COLLATE pg_catalog."default" NOT NULL,
    last_activity integer NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario serial NOT NULL,
    nombre character varying(80) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(80) COLLATE pg_catalog."default" NOT NULL,
    email character varying(120) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(200) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(40) COLLATE pg_catalog."default",
    estado character varying(15) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVO'::character varying,
    id_rol integer,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuario_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.venta
(
    id_venta serial NOT NULL,
    id_cliente integer NOT NULL,
    id_orden integer,
    fecha_venta timestamp without time zone NOT NULL DEFAULT now(),
    moneda character varying(10) COLLATE pg_catalog."default" DEFAULT 'BOB'::character varying,
    estado character varying(15) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDIENTE'::character varying,
    subtotal numeric(12, 2) DEFAULT 0,
    descuento numeric(12, 2) DEFAULT 0,
    total numeric(12, 2) DEFAULT 0,
    CONSTRAINT venta_pkey PRIMARY KEY (id_venta)
);

CREATE TABLE IF NOT EXISTS public.venta_detalle
(
    id_detalle serial NOT NULL,
    id_venta integer NOT NULL,
    id_producto integer,
    id_servicio integer,
    descripcion character varying(200) COLLATE pg_catalog."default",
    cantidad numeric(12, 3) NOT NULL,
    precio_unit numeric(12, 2) NOT NULL,
    descuento numeric(12, 2) DEFAULT 0,
    subtotal numeric(12, 2) NOT NULL,
    CONSTRAINT venta_detalle_pkey PRIMARY KEY (id_detalle)
);

ALTER TABLE IF EXISTS public.cotizacion
    ADD CONSTRAINT cotizacion_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cotizacion
    ADD CONSTRAINT cotizacion_id_servicio_fkey FOREIGN KEY (id_servicio)
    REFERENCES public.servicio (id_servicio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cotizacion_detalle
    ADD CONSTRAINT cotizacion_detalle_id_cotizacion_fkey FOREIGN KEY (id_cotizacion)
    REFERENCES public.cotizacion (id_cotizacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cotizacion_detalle
    ADD CONSTRAINT cotizacion_detalle_id_producto_fkey FOREIGN KEY (id_producto)
    REFERENCES public.producto (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cuota
    ADD CONSTRAINT cuota_id_plan_fkey FOREIGN KEY (id_plan)
    REFERENCES public.plan_pago (id_plan) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cuota_pago
    ADD CONSTRAINT cuota_pago_id_cuota_fkey FOREIGN KEY (id_cuota)
    REFERENCES public.cuota (id_cuota) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cuota_pago
    ADD CONSTRAINT cuota_pago_id_recibo_fkey FOREIGN KEY (id_recibo)
    REFERENCES public.recibo (id_recibo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orden_trabajo_tecnico
    ADD CONSTRAINT orden_trabajo_tecnico_id_orden_fkey FOREIGN KEY (id_orden)
    REFERENCES public.ordentrabajo (id_orden) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orden_trabajo_tecnico
    ADD CONSTRAINT orden_trabajo_tecnico_id_tecnico_fkey FOREIGN KEY (id_tecnico)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ordentrabajo
    ADD CONSTRAINT ordentrabajo_id_cotizacion_fkey FOREIGN KEY (id_cotizacion)
    REFERENCES public.cotizacion (id_cotizacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.plan_pago
    ADD CONSTRAINT plan_pago_id_venta_fkey FOREIGN KEY (id_venta)
    REFERENCES public.venta (id_venta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_id_categoria_fkey FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.recibo
    ADD CONSTRAINT recibo_id_venta_fkey FOREIGN KEY (id_venta)
    REFERENCES public.venta (id_venta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.recibo_detalle_pago
    ADD CONSTRAINT recibo_detalle_pago_id_recibo_fkey FOREIGN KEY (id_recibo)
    REFERENCES public.recibo (id_recibo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_id_rol_fkey FOREIGN KEY (id_rol)
    REFERENCES public.rol (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.venta
    ADD CONSTRAINT venta_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.venta
    ADD CONSTRAINT venta_id_orden_fkey FOREIGN KEY (id_orden)
    REFERENCES public.ordentrabajo (id_orden) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.venta_detalle
    ADD CONSTRAINT venta_detalle_id_producto_fkey FOREIGN KEY (id_producto)
    REFERENCES public.producto (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.venta_detalle
    ADD CONSTRAINT venta_detalle_id_servicio_fkey FOREIGN KEY (id_servicio)
    REFERENCES public.servicio (id_servicio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.venta_detalle
    ADD CONSTRAINT venta_detalle_id_venta_fkey FOREIGN KEY (id_venta)
    REFERENCES public.venta (id_venta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;